---
title: "MAplots"
author: "Tamara Keßler"
date: '2022-09-13'
output: html_document
---

```{r supress warnings, echo=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, # supress warnings per default 
  message = FALSE  # supress messages per default 
)
```

```{r clear workspace, echo=FALSE}
rm(list = ls())
```

```{r libraries, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
#library(readbulk)
#library(cowplot)
```

```{r ggplot theme, echo=FALSE}
theme_set(theme_minimal() +
  theme(
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    panel.border = element_rect(colour = "black", fill=NA)
  ))

options(width=90, scipen = 999)
```

```{r read data, echo=FALSE}

behav <- read_csv2('C:/Users/tamar/Desktop/mscthesis/mscthesis/behavtidy.csv')

```

```{r plot}

behav %>%
  ggplot(
    aes(
      x = Test, 
      y = BehavScore,
      color = Group,
      fill = Group
    )
  ) + geom_boxplot(alpha = 0.5) +
  scale_color_manual(
    values = c("palegreen3","orange","darkgreen","darkorange2")
  ) + scale_fill_manual(
    values = c("palegreen3","orange","darkgreen","darkorange2")
  )

```