---
title: "MAplots"
author: "Tamara Keßler"
date: '2022-09-13'
output: html_document
---

```{r supress warnings, echo=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, # supress warnings per default 
  message = FALSE  # supress messages per default 
)
```

```{r clear workspace, echo=FALSE}
rm(list = ls())
```

```{r libraries, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(cowplot)
```

```{r ggplot theme, echo=FALSE}
theme_set(theme_minimal() +
  theme(
    axis.line = element_line(colour = "black"),
    axis.ticks = element_line(colour = "black"),
    axis.text = element_text(colour = "black"),
    panel.border = element_rect(colour = "black", fill=NA)
  ))

options(width=90, scipen = 999)
```

```{r read data, echo=FALSE}

#behav <- read_csv2('C:/Users/tamar/Desktop/mscthesis/mscthesis/behavtidy.csv')
#NvsC <- read_csv('C:/Users/Sperber/Desktop/mscthesis/forR/Discon_NvsCtidy.csv')
#ModelAcc <- read_csv('C:/Users/Sperber/Desktop/mscthesis/forR/PrecisionAllModels.csv')
#ModelAcc <- read_csv('C:/Users/tamar/Desktop/mscthesis/mscthesis/forR/PrecisionAllModels.csv')
sspls = read_csv('D:/Tamara/Diskonnektionen/SSPLs/tidymaxSSPLs.csv')

```

```{r plot behav}

behav %>%
  ggplot(
    aes(
      x = Test, 
      y = BehavScore,
      color = Group,
      fill = Group
    )
  ) + geom_boxplot(alpha = 0.5) +
  scale_color_manual(
    values = c("palegreen3","orange","darkgreen","darkorange2")
  ) + scale_fill_manual(
    values = c("palegreen3","orange","darkgreen","darkorange2")
  )

```

```{r histo SSPLs}

meanF <- sspls %>%
  filter(Sex == "F") %>%
  pull(MaxSSPL) %>%
  mean

meanM <- sspls %>%
  filter(Sex == "M") %>%
  pull(MaxSSPL) %>%
  mean

sspls %>%
  group_by(Sex) %>%
  ggplot(
    aes(
      x = MaxSSPL,
      color = Sex,
      fill = Sex
    )
  ) + geom_bar(
    position = "dodge"
  ) + scale_color_manual(
    values = c("darkgreen", "darkorange2")
  ) + scale_fill_manual(
    values = c("darkgreen", "darkorange2")
  ) + geom_vline(
    xintercept = meanF,
    linetype = "dashed",
    color = "darkorange3"
  ) + annotate(
    "text", 
    x = meanF - 0.1, 
    y = 60,
    label = "mean(Female)", 
    angle = 90,
    size = 3
  ) + geom_vline(
    xintercept = meanM,
    linetype = "dashed",
    color = "darkgreen"
  ) + annotate(
    "text", 
    x = meanM - 0.1, 
    y = 60,
    label = "mean(Male)", 
    angle = 90,
    size = 3
  ) + labs(
    x = "Max Value of SSPL Increase",
    y = "n"
  )


```

```{r distribution boxplot SSPL}

sspls %>%
  ggplot(
    aes(
      x = Sex, 
      y = MaxSSPL,
      color = Sex,
      fill = Sex
    )
  ) + geom_violin(alpha = 0.5) +
  scale_color_manual(
    values = c("darkgreen","darkorange2")
  ) + scale_fill_manual(
    values = c("darkgreen","darkorange2")
  ) + geom_hline(
    yintercept = meanF,
    linetype = "dashed",
    color = "darkgreen"
  ) + geom_hline(
    yintercept = meanM,
    linetype = "dashed",
    color = "darkorange2"
  ) + geom_jitter(
    alpha = 0.3,
    width = 0.2
  )
  

sspls %>%
  ggplot(
    aes(
      x = MaxSSPL,
      color = Sex,
      fill = Sex
    )
  ) + geom_density(alpha = 0.5) +
  scale_color_manual(
    values = c("darkgreen","darkorange2")
  ) + scale_fill_manual(
    values = c("darkgreen","darkorange2")
  ) + geom_vline(
    xintercept = meanF,
    linetype = "dashed",
    color = "darkorange3"
  ) + annotate(
    "text", 
    x = meanF - 0.1, 
    y = 0.7,
    label = "mean(Female)", 
    angle = 90,
    size = 3
  ) + geom_vline(
    xintercept = meanM,
    linetype = "dashed",
    color = "darkgreen"
  ) + annotate(
    "text", 
    x = meanM - 0.1, 
    y = 0.7,
    label = "mean(Male)", 
    angle = 90,
    size = 3
  ) + labs(
    x = "Max Value of SSPL Increase",
    y = "n"
  )

```

```{r plot performance}

NvsC %>%
  ggplot(
    aes(
      x = Correct,
      y = 1,
      color = Label,
      fill = Label
    )
  ) + geom_jitter(
    width = 0.2,
    size = 3,
    alpha = 0.6
  ) +
  scale_x_discrete(
    labels = c("steelblue","Non-Neglect")
  ) + scale_color_manual(
    values = c("steelblue", "darkred")
  )

# NvsC %>%
#   ggplot(
#     aes(
#       x = Predict,
#       color = Label,
#       fill = Label
#     )
#   ) + geom_bar(
#    position = "dodge"
#   ) + scale_x_continuous(
#     breaks = 1:2,
#     labels = c("Neglect", "Non-Neglect")
#   )+ labs(
#     x = "Predicted Label"
#   ) + scale_fill_manual(
#     values = c("steelblue", "darkred")
#   ) + scale_color_manual(
#     values = c("steelblue", "darkred")
#   )
```

```{r sumstats acc}

twoclass <- ModelAcc %>%
  filter(
    Classification != "Four"
  ) %>% group_by(
    Map, Classification
  ) %>% summarise(
    ModelMean = mean(ModelPrecision)
  ) %>% ggplot(
    aes(
      x = Classification,
      y = ModelMean,
      color = Map,
      fill = Map
    )
  ) + geom_col(
    position = "dodge"
  ) + geom_hline(
    yintercept = 50,
    linetype = "dashed"
  ) + theme(legend.position='none') +
  ylim(0,100) +
  scale_color_manual(
    values = c("steelblue", "darkorange")
  ) +
  scale_fill_manual(
    values = c("steelblue", "darkorange")
  ) + labs(
    y = "Prediction Accuracy (%)",
    x = ""
  )

fourclass <- ModelAcc %>%
  filter(
    Classification == "Four"
  ) %>% group_by(
    Map, Classification
  ) %>% summarise(
    ModelMean = mean(ModelPrecision)
  ) %>% ggplot(
    aes(
      x = Classification,
      y = ModelMean,
      color = Map,
      fill = Map
    )
  ) + geom_col(
    position = "dodge"
  ) + geom_hline(
    yintercept = 25, 
    linetype = "dashed"
  ) + ylim(0,100) +
  labs(
    y = "",
    x = "",
    color = "Model",
    fill = "Model"
  ) +
  scale_color_manual(
    values = c("steelblue", "darkorange")
  ) +
  scale_fill_manual(
    values = c("steelblue", "darkorange")
  ) 

plot_grid(twoclass, fourclass)

```

```{r acc notsplit}

# ModelAcc %>%
#   group_by(
#     Map, Classification
#   ) %>% summarise(
#     ModelMean = mean(ModelPrecision)
#   ) %>% ggplot(
#     aes(
#       x = Classification,
#       y = ModelMean,
#       color = Map,
#       fill = Map
#     )
#   ) + geom_col(
#     position = "dodge"
#   ) + geom_hline(
#     yintercept = 50,
#     linetype = "dashed", 
#     color = "black"
#   ) + geom_hline(
#     yintercept = 25,
#     linetype = "dotted", 
#     color = "black"
#   ) + theme(legend.position='none') +
#   ylim(0,100)


```